# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('dv', 'development'), ('ps', 'personal')], default='dv', max_length=2),
        ),
    ]
