# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-25 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20181121_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='small_title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
