# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-25 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_article_small_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='checkbox',
            field=models.BooleanField(default=True),
        ),
    ]
