# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-25 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_comment_checkbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
