# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-25 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20181125_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='checkbox',
            new_name='approved_comment',
        ),
    ]
